### ISSUE TITLE
Refresh Segment Count mit neuem Segmentierungsalgorithmus

### ISSUE THREAD

**Issue by EXMARaLDA** [Exmaralda-Org/exmaralda#1]
wenn man segment count refresh macht und eine transkription mit einer neuen segmentierungsalgorithm zerlegt hat, refresht es nciht so richtig, die alten (z.B. HIAT:...) stehen noch da neben den neuen (z.B: GEN:...).

**Comment by EXMARaLDA** [comment]
Kein Fehler im eigentlichen Sinne. Will wirklich jeder die alte Information verlieren?

**Comment by Herrner** [comment]
Man könnte fragen, ob die alten wegsollen.

**Comment by Herrner** [comment]
"refresh segment count" now asks to remove old segment counts. removes all description keys that match `#(..).*:.*` not tested thoroughly.
