### ISSUE TITLE
.exb-Linking to Partitur Editor somehow broken?

### ISSUE THREAD

**Issue by Herrner** [Exmaralda-Org/exmaralda#100]
Double klicking on an .exb file brings up this:

![image](https://user-images.githubusercontent.com/2045460/27021815-1d06f6da-4f4b-11e7-9003-1fd781982db3.png)

But there's obviously no such .exe anymore.

**Comment by Herrner** [comment]
Wohoo! Issue #100!

**Comment by berndmoos** [comment]
The whole PartiturEditorWithSun variant is gone (on Windows). File associations can remain from a previous installation. It is probably best to uninstall EXMARaLDA, then choose "Asscociate files" (or so) in the installation wizard. Can't think of any other way. What a sad issue for #100...

**Comment by berndmoos** [comment]
This is explained, hence resolved.
