### ISSUE TITLE
Pause not working properly

### ISSUE THREAD

**Issue by me-kell** [Exmaralda-Org/exmaralda#112]
When Pressing Ctrl-F5 the state of the buttons (Play, Pause, Stop and others) changes inconsistently.
To reproduce it:

- Create new EXMARaLDA Project
- Add media file
- Click on the oscillogram
- Press Ctrl-F4 (Play)
- Press Ctrl-F5 (Pause) 

If you press Ctrl-F5 again it plays, next time it pauses. But if you repeat it again and again (what you usually do when transcribing) after few times the buttons change state (enabled/disabled) inconsistently and at some time you can only restart playing with Ctrl-F4. Pressing repeatedly Ctrl-F5 again ends with all the buttons disabled (sometimes only play remains enabled). After this point neither Ctrl-F4 nor Ctrl-F5 works.

A similar problem can be reproduced without pressing Ctrl-Fx keys but directly pressing the Play and Pause buttons.

Environment: Windows 7, Java 1.8.0_101, Exmaralda 1.6,, Build 20170509.2123

**Comment by berndmoos** [comment]
Will check this. Might take a while, though, because of vacation approaching...

**Comment by me-kell** [comment]
The wrong behaviour described above occurs with "JDS Media Player". Tested in diferent windows machines.

Changing to "JMF Player" works fine, as expected. Changing to "BAS Audio Player" works fine, but has some problems with the cursor in the oscillograph while playing after having paused a few times.

BTW: When users change to JMF-Player and restart the PartitureEditor they get a warning saying that the JMF-Player is not the recommended default player, that the recommended default player is JDS-Player. And the dialog asks the user to switch to the recommended player. This dialog may be frustrating for non technical users. I'd recommend not to show this dialog until the above behaviour is fixed.

**Comment by berndmoos** [comment]
For JDS player: the problem seems to be that sometimes (irregularly), the action for PAUSE has the effect of STOP. This is not a problem of the keyboard shortcuts, but of the actions themselves (or the events posted). The problem also occurs when the same actions are carried out via the buttons. Stay tuned....

**Comment by berndmoos** [comment]
For JDS player: this seems to be the same threading issue as in #98. Using "invokeLater" in processPlayableEvent(...) of AbstractTimeviewPartiturPlayerControl seems to solve the issue.

**Comment by berndmoos** [comment]
For BAS player: the cursor problem is reproducible, it seems to be directly related to the PAUSE action. There is no such problems for other player actions. Stay tuned once more...

**Comment by berndmoos** [comment]
For BAS player: PAUSE and RESUME actions completely neglect the BAS player internal play thread. Changed that now, it seems to resolve the issue.

**Comment by berndmoos** [comment]
Both issues adressed - need to watch this a little further. Windows preview is under way.

**Comment by berndmoos** [comment]
Behold! Problem with JDS seems to persist on Windows 10 (former tests were on Windows 7...). BAS player seems to be fine on Windows 10, too, though (so no need to revive the JMF player...)

**Comment by berndmoos** [comment]
Test on another Win 10: JDS problem is **not** solved.
