### ISSUE TITLE
Windows 10 sometimes writes broken exbs that look like binaries

### ISSUE THREAD

**Issue by anneferger** [Exmaralda-Org/exmaralda#116]
The content is the same number in hex a hundred times, now happened on two different computers of two different users, but both windows 10 (see OTRS)

Maybe it's only in combination with force reboot, but it should be checked

**Comment by anneferger** [comment]
Yes, it propably only happens in combination with forced reboots.

**Comment by berndmoos** [comment]
I don't think there is anything we can or should do about it. Can we close the issue?

**Comment by anneferger** [comment]
Yes, and nobody else experienced it recently anyways
