### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hannahedeland** [Exmaralda-Org/exmaralda#117]
The manuals should be included here, but where (cf. #79) and should we also include the Sextant manual? And FOLKER, OrthoNormal, TEI Drop?

**Comment by berndmoos** [comment]
What is 'here'? The FOLKER manual is on the IDS website. There is as yet no manual for OrthoNormal or TEIDrop.

**Comment by hannahedeland** [comment]
Maybe in exmaralda/docs/ - and if we can have stuff like :guilabel: to mark up GUI text as such and other things then maybe even in rst... The ISO/TEI-related documentation will need a home :)

**Comment by Herrner** [comment]
Und was ist [hiermit](https://www.fdr.uni-hamburg.de/search?page=1&size=100&q=exmaralda&subtype=softwaredocumentation) - das könnte man ja im Zweifel verlinken. Oder geht's um die Quellen?

**Comment by hannahedeland** [comment]
Genau, die Quellen, sie liegen noch(?) aus historischen Gründen aufm HZSK-Server, aber da passiert wohl eher nicht so viel(?), und sie müssten ja auf einfache Weise Updates bekommen können, wenn neue Funktionen hinzukommen usw. - aber es geht hauptsächlich nur um die Manuals, der Rest kann wohl eher nicht weiterleben (und im FDR stimmt übrigens dort der angegebene Autor nicht überall, aber bei den Meisterwerken ist das vielleicht eher sein Problem hehe).

**Comment by berndmoos** [comment]
The sources of all documentation shalle henceforthe be collected and maintained in https://github.com/Exmaralda-Org/exmaralda-docs
