### ISSUE TITLE
Menu bar disappears on MAC OS 10.13 High Sierra

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#125]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=520176

see comment 72 (courtesy of Kawanna)

**Comment by berndmoos** [comment]
see also Ticket#2017100510000011

**Comment by Herrner** [comment]
Can't reproduce, neither w/ Oracle Java 1.8 nor w/ Apple Java 1.6.

**Comment by berndmoos** [comment]
Suspicious error message in FOLKER log (not sure if it is related to this issue):

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Non-Java exception raised, not handled! (Original problem: Deprecated in 10_12... DO NOT EVER USE CGSEventRecord directly. Bad things, man.... bad things.)

**Comment by berndmoos** [comment]
Gloomy news on https://de.mathworks.com/matlabcentral/answers/368549-java-error-on-launching-matlab-r2011a-on-mac-os-highsierra-10-13-1?requestedDomain=www.mathworks.com:

- "Yes, it is really unfixable. El Capitan was the last version in which you could reliable configure preferences multiple Java versions."

- "Sierra broke backwards compatibility in a number of respects. High Sierra broke it even further."

- "That version of MATLAB is not supported on high sierra and probably cannot be made to work"

**Comment by berndmoos** [comment]
Same on http://imagej.1557.x6.nabble.com/OS-X-10-13-High-Sierra-ImageJ-Java-6-and-text-editing-td5019713.html: 

- "My advice would be to use an older version of MacOS if you continue to need 
Java 6 functionality. "

**Comment by Herrner** [comment]
![image](https://user-images.githubusercontent.com/2045460/33421998-5acef09a-d5b4-11e7-8e14-d62647fb6f4a.png)
Perfect Harmony. I want to reproduce that thing!

**Comment by berndmoos** [comment]
We cannot reproduce it, the user who could says the problem is gone after an OS update. So I'm closing...
