### ISSUE TITLE
Edit tiers.... menu: Changes in column view aren't saved 

### ISSUE THREAD

**Issue by anneferger** [Exmaralda-Org/exmaralda#137]
When clicking on Tier>Edit tiers... in PE a writable column view of all the tiers opens, changes can be made in it, but clicking on "OK" doesn't save them. The Edit tier... button next to the overview works fine. 
Noticed in it in INEL e.g.

Two ways to fix it:

* Make column view read-only (not so nice if you have many tiers and want to change much)
* Save the changes made in the column view (probably takes longer....)

**Comment by berndmoos** [comment]
Could be useful and not too complicated. We would need a real table model and table cell editors, though, because some columns (e.g. ID) should not be editable, others (e.g. annotation mismatches) need to update according to changes in other columns.

**Comment by berndmoos** [comment]
Worked on this quite a lot, most changes should now be tranferred to the Partitur when the dialog is closed

**Comment by berndmoos** [comment]
I guess that one is working
