### ISSUE TITLE
Remote corpora don't work anymore in EXAKT

### ISSUE THREAD

**Issue by Herrner** [Exmaralda-Org/exmaralda#155]
the whole www1.uni-hamburg.de-webserver does not exist anymore. Maybe remove the corpus lookup for the time beeing.

**Comment by berndmoos** [comment]
The remote corpora won't come back. Or will they?

**Comment by berndmoos** [comment]
Related to #48

**Comment by berndmoos** [comment]
There are INEL corpora in the INEL Langzeitspeicher which are / can be accessed as EXAKT remote corpora. See mail by Problemberg.

**Comment by berndmoos** [comment]
TL creates a corpus catalog for INEL corpora, to be integrated in EXAKT. Existing catalog is at http://www.exmaralda.org/xml/EXMARaLDACorpusCatalog.xml

**Comment by berndmoos** [comment]
The demo corpus (version 1.1) is now available again at:

https://s3-uhh.lzs.uni-hamburg.de/gwiss-exmaralda/remote/demokorpus-1.1/EXMARaLDA_DemoKorpus.coma

A corresponding corpus catalogue, consisting of just the one corpus is at 

http://agd.ids-mannheim.de/xml/EXMARaLDACorpusCatalog.xml

INEL is cordially invited to make a corpus catalogue for their corpora (this is not an Auftrag by TS).

**Comment by berndmoos** [comment]
At least they are not not working. If somebody wants a catalogue integrated into the distribution, they can say so and reopen this issue.
