### ISSUE TITLE
Bug in EXAKT collection creation

### ISSUE THREAD

**Issue by daniel-jettka** [Exmaralda-Org/exmaralda#165]
Attribute @category missing in output of new tiers from template

**Comment by daniel-jettka** [comment]
add following to https://github.com/EXMARaLDA/exmaralda/blame/master/src/org/exmaralda/exakt/resources/SearchResults2EXBs.xsl#L262

`category="{@category}"`

**Comment by berndmoos** [comment]
anything for me to do? @hzsk-dj?

**Comment by daniel-jettka** [comment]
Fixed it, but I am afraid it has to be merged into EXMARaLDA/exmaralda now (created pull request), and this has to be built then. Or if you know an easier way to do the following... @berndmoos 


> add following to https://github.com/EXMARaLDA/exmaralda/blame/master/src/org/exmaralda/exakt/resources/SearchResults2EXBs.xsl#L262
> 
> `category="{@category}"`

**Comment by berndmoos** [comment]
> Or if you know an easier way 

Merging IS the easiest way :-)

**Comment by daniel-jettka** [comment]
Thanks, but the preview does not seem to incorporate the change. Could you double-check if you built the newest version? @berndmoos

**Comment by berndmoos** [comment]
Me stupid: have to merge, PULL, build, upload. Forgot the pull. New preview under way...

**Comment by berndmoos** [comment]
@hzsk-dj : Geht's jetzt? Ich weiß leider gar nicht, was ich da testen müsste...

**Comment by daniel-jettka** [comment]
@berndmoos Jetzt gehts. Danke! Fürs Protokoll, ich habs folgendermaßen getestet: 
- Demo-Korpus in EXAKT geöffnet
- nach "dieser" gesucht und per "Concordance > Create collection from concordance..." eine Kollektion erstellt
- die neue Kollektion über "Generate corpus" in EXAKT geöffnet, dabei segmentiert
- wieder nach "dieser" gesucht und das funktionierte
