### ISSUE TITLE
New ELAN player on MAC?

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#173]
Somebody with a Mac needs to test if this [experimental ELAN version](https://tla.mpi.nl/tools/tla-tools/elan/download/) is okay for audio and video from the EXMARaLDA test battery. 

https://www.exmaralda.org/files/MEDIA-TEST-BATTERY.zip

I can. Can @Herrner ? 

> This is to announce a test version of ELAN 5.4 for macOS (labeled ELAN 
> 5.4-AVFX).
> 
> Background:
> ELAN is written in the Java programming language. Our Java code still 
> needs to be compatible with the outdated version Java 6. The reason for 
> this dependency is the way the Cocoa and QuickTime based media player of 
> macOS is integrated in ELAN. This depends on certain features of Apple's 
> implementation of Java 6 for macOS.
> Newer versions of Java for macOS are developed by Oracle (current 
> version Java 11) and the old approach of integrating video is not 
> supported in those versions. And it seems the way 'native' video 
> components can be integrated on other operating systems, is not 
> supported on macOS either in Java 8 or above.
> 
> In order to be able to remove the Java 6 dependency and move on to Java 
> 8 (and eventually Java 10 or 11) we tried a few things:
> 1) an ELAN video player based on the JavaFX media player (JavaFX is an 
> integral part of Java 8 and higher). Two test version of ELAN containing 
> this JavaFX player were released earlier. The main issues with this 
> player are the limited file format support (mainly .mp4 and .wav), the 
> overshoots at starting and stopping playback and limited support for 
> frame stepping. This player is again available in this ELAN 5.4-AVFX version
> 
> 2) a player based on Apple's current, main framework for time-based 
> audiovisual media, AVFoundation. This player performs the decoding of 
> video in 'native' code but the display of the frame images is performed 
> in ELAN's Java code. The downside of this approach is that only the 
> decoding part can benefit from available hardware optimizations. 
> Therefore this player, in ELAN labeled 'JAVF - Java with AV Foundation', 
> demands more of the CPU power and internal memory.
> 
> While we will continue to investigate alternative approaches, it would 
> be good to have some feedback of users, to see if this current JAVF 
> approach has a future or not. (Not everything that is usually available 
> in the (right-mouse-button) context menu of ELAN video players has been 
> implemented yet.)
> 
> This test release of ELAN includes a Java 8 runtime environment, so 
> there is no need to install that separately. The .app package structure 
> is (related to that) different from the structure in the 'official' ELAN 
> versions. This test release can be downloaded from the usual download page:

https://tla.mpi.nl/tools/tla-tools/elan/download/

**Comment by Herrner** [comment]
I still have a mac, but not one capable of running Mojave (10.14); should I still try with whatever rubbish MacOS I have?

**Comment by berndmoos** [comment]
Yeah, try that rubbish thing. Throw that ELAN on the garbage Mac!

**Comment by berndmoos** [comment]
Take #1 on 10.10.5 (Yosemite) - ELAN won't start / Console:

`20.12.18 13:51:02,000 kernel[0]: AMFI: Error! There is a null code directory pointer. This is an unexpected condition.
20.12.18 13:51:02,074 ELAN_5.4-AVFX[53660]: /Users/thomasschmidt/Desktop/ELAN_5.4-AVFX.app/Contents/MacOS/libpackager.dylib not found.
20.12.18 13:51:02,075 com.apple.xpc.launchd[1]: (nl.mpi.elan.190596[53660]) Service exited with abnormal code: 1
20.12.18 13:51:04,799 taskgated[96]: no application identifier provided, can't use provisioning profiles [pid=53662]
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:04,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:04,893 com.apple.xpc.launchd[1]: (com.avira.antivirus.iris) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
20.12.18 13:51:14,912 taskgated[96]: no application identifier provided, can't use provisioning profiles [pid=53664]
20.12.18 13:51:14,996 sandboxd[386]: ([48]) appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 sandboxd[386]: ([48]) appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:15,003 sandboxd[386]: ([48]) appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:15,000 kernel[0]: Sandbox: appleeventsd(48) deny mach-lookup com.apple.ocspd
20.12.18 13:51:15,006 sandboxd[386]: ([48]) appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,010 sandboxd[386]: ([48]) appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,013 sandboxd[386]: ([48]) appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,017 com.apple.xpc.launchd[1]: (com.avira.antivirus.iris) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
20.12.18 13:51:15,018 sandboxd[386]: ([48]) appleeventsd(48) deny file-read-metadata /Library
20.12.18 13:51:15,021 sandboxd[386]: ([48]) appleeventsd(48) deny file-read-metadata /Library
`

**Comment by berndmoos** [comment]
There is another version which has a JRE 11 integrated:

https://www.mpi.nl/tools/elan/ELAN_5-4-AVFX-J11_mac.zip

On my (and Han's) Yosemite, in the Finder the application is marked by strike-through overlay icon, indicating that it can't be run. The message when trying to launch it: 

![image](https://user-images.githubusercontent.com/13796493/51676604-6a198d80-1fd7-11e9-9c3e-0c915a537b03.png)

Or, in English, on Han's computer: You can't use this version of the application ELAN (...). You have OS X 10.10.4. The application requires OS X 10.13 or later. 

However, going into the package and dragging the executable (ELAN_5-4-AVFX-J1_mac) from Contents/MacOS into a Terminal window will launch ELAN. 

The player works okay with the MPEG-4 from the Test battery. Many subsequent clicks on "Play selection", playback sometimes does not stop at the end of the selection. There is a little overshot, but all in all, this seems to be an okay solution.

**Comment by berndmoos** [comment]
see #199

**Comment by berndmoos** [comment]
Updates for ELAN version 6.3:

- the AVF player on macOS sometimes wouldn't stop at the end of the selection, this is now improved
- fixed .wav support for 8-bit stereo and added support for 32-bit .wav files and 32-bit audio from video

Might be worthwhile to update the ELAN libraries accordingly

**Comment by berndmoos** [comment]
If that's still an issue, it is not this issue.
