### ISSUE TITLE
Move to tier for more than one event

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#176]
Feature request by NAMD project

**Comment by berndmoos** [comment]
Preview with test request to NAMD project (TicketID=4385)

**Comment by berndmoos** [comment]
Seems to work.

**Comment by sarkipo** [comment]
"Move to tier" for more than one event seems to be there in the preview of 20230325 but not there in the current release/preview anymore... 
![grafik](https://github.com/Exmaralda-Org/exmaralda/assets/11090777/d2353af2-fbf7-417a-a8f7-98eb13e89d24)
Was it intended?

**Comment by sarkipo** [comment]
A related wish would be "Move to another speaker" (same tier category, different speaker)
Ideally also for a rectangular selection (at least in the case when there is unambiguously one destination tier available for each source tier)

**Comment by berndmoos** [comment]
> Was it intended? 

No, not intended. Fixing this in the next preview.

**Comment by sarkipo** [comment]
Thanks a lot!
