### ISSUE TITLE
repeated use of File > New from wizard... generates odd symbols in tiers (Partitur Editor)

### ISSUE THREAD

**Issue by RunaRagnarok** [Exmaralda-Org/exmaralda#197]
It comes up by using the same coma file, don't know if there is the same problem with a different one

**Comment by berndmoos** [comment]
Methinks I fixed that some time in September or so (?), see https://support.clarin-d.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=5239

**Comment by berndmoos** [comment]
@RunaRagnarok: ist das jetzt okay?

**Comment by RunaRagnarok** [comment]
Ich teste es nächste Woche

**Comment by berndmoos** [comment]
@RunaRagnarok Getestet?

**Comment by RunaRagnarok** [comment]
Ja funktioniert jetzt, man muss nur im Wizard erst die alten Spuren mit den falschen Symbolen löschen und neu anlegen, dann kommen auch keine neuen Symbole wieder.
