### ISSUE TITLE
Kein Filename-Element, wenn nachträglich .wav-Dateien hinzugefügt werden.

### ISSUE THREAD

**Issue by EXMARaLDA** [Exmaralda-Org/exmaralda#2]
Wenn man weitere (wav-)Dateien hinzufügt, wird anderes XML geschrieben als wenn die Dateien über die Transkriptionen ins Korpus kommen, zumindest kriegt man dann kein Filename-Element

**Comment by Herrner** [comment]
Will man das Element denn haben oder nicht?

**Comment by hannahedeland** [comment]
Ich denke, heutzutage will man es nicht unbedingt mehr, das war wohl eine frühere Version des Schemas. Ist auf jeden Fall sehr unwichtig, kann m.E. zu.

**Comment by Herrner** [comment]
Ich sehe gerade, dass sich "Suchen und Ersetzen im Korpus" auf eine Filename-Element verlässt... ist also auch wieder komplizierter, als ich dachte.

**Comment by Herrner** [comment]
Jetzt bekommt man (hoffentlich) ein Filename-Element.
