### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#203]
There are larger parts of 

- deprecated code (as in ../deprecated/...)
- unused code (as in ../sbcsae/...)
- code that will become obsolete with the switch to JDK11 (see issue #199)
- source code which had better be integrated as bin library (tt4j and weblicht)

Cleaning up will also mean that the number of libraries can be considerably reduced. I'll do it or die.

**Comment by berndmoos** [comment]
Cleaned up, and it is still running (from the IDE)...

**Comment by Herrner** [comment]
![image](https://user-images.githubusercontent.com/2045460/74324642-9d1bf400-4d87-11ea-9ab2-a199e97ec5bd.png)

**Comment by berndmoos** [comment]
Code is less filthy than before, so close dis

**Comment by berndmoos** [comment]
Some more code that can be removed (we have a memory fork, just in case):
- hzsk
- aligner
- masker
- tagger
-

**Comment by berndmoos** [comment]
Not masker, you fool!
