### ISSUE TITLE
Sign and Notarize MAC OS distributions

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#205]
.. so the warnings go away:

https://stackoverflow.com/questions/252226/signing-a-windows-exe-file
https://developer.apple.com/developer-id/

**Comment by berndmoos** [comment]
Applied for Membership in Apple Developer Program (IDS as Organization)

**Comment by berndmoos** [comment]
No chance to do that now. Would need membership not via IDS but via X

**Comment by Herrner** [comment]
How much?

**Comment by berndmoos** [comment]
Seems I do have an account after all...

**Comment by berndmoos** [comment]
https://developer.apple.com/forums/thread/682871
https://developer.apple.com/forums//thread/718795

**Comment by berndmoos** [comment]
For the record, here is what I did for signing a MAC OS application:

1. Use Keychain app on the MAC to generate a certificate request: "Keychain Access > Certificate Assistant > Request a Certificate From a Certificate Authority" // Enter E-Mail // Leave CA Email address blank // Choose saved to disk
2. Login to developer.apple.com and generate a certificate of type "Developer ID Application"
3. Go back to Keychain Access // Make sure to select "System" under "System Keychains" ("iCloud" is preselected) // Import certificate via "File > Import Items..." 
4. Go back to ant and jpackage

That is so easy I could throw up all night.

**Comment by berndmoos** [comment]
Signed DMG works, but MAC OS is still saying: "cannot be opened because it cannot be checked for malicious software" (right click > open will do)

**Comment by berndmoos** [comment]
Signed DMG works except ... Unsatisfied Link Error for AVFPlayer

```
WARNING: Could not load native utility library (libJNIUtil.dylib): no JNIUtil in java.library.path: /Applications/PartiturEditor.app/app/native
Nov 01, 2022 8:32:41 AM nl.mpi.avf.player.AVFBasePlayer <clinit>
WARNING: Could not load native library (libAVFPlayer.dylib): no AVFPlayer in java.library.path: /Applications/PartiturEditor.app/app/native

```

This is nothing to do with signing -- the same error occurs with the local DMG before up-/downloading.
And it's also not because of type=dmg, it's not working either with type=app-image -- could be good news

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/199200970-8aa9f219-138b-4052-aa98-324dae703d9c.png)

**Comment by berndmoos** [comment]
* type=dmg works (including AVF, the path was missing the initial "Content/") 
* still have to right click, though, because of "malicious software checking"
* Very mysterious: why the bleedin' shyte is it uploading all DMGs except EXAKT??

**Comment by berndmoos** [comment]
Believe it or not: it seems I can notarize (currently the M1 distribution) like so:

1. Generate an "application specific password" via https://appleid.apple.com/

2. Store that application specific password in the keychain:

`xcrun notarytool store-credentials "NOTARIZATION_PASSWORD" --apple-id "MY_APPLE_ID" --team-id MY_TEAM_ID --password APPLICATION_SPECIFIC_PASSWORD
`

3. Start Notarization: 

`xcrun notarytool submit /Users/thomasschmidt/EXMARaLDA_Build/jpackage/EXAKT_DMG/EXAKT-1.4.dmg --keychain-profile "NOTARIZATION_PASSWORD" --wait
`

It will take about 5 to 10 minutes until the process returns with verdict "Invalid". I can get the log file:

`xcrun notarytool log SUBMISSION_ID --keychain-profile "NOTARIZATION_PASSWORD"
`
... and it will tell me that the binaries inside the JavaFX jars are not signed and do not have a secure timestamp:

  ```
"issues": [
    {
      "severity": "error",
      "code": null,
      "path": "EXAKT-1.4.dmg/EXAKT.app/Contents/app/lib/javafx-graphics-11-mac.jar/libjavafx_iio.dylib",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "EXAKT-1.4.dmg/EXAKT.app/Contents/app/lib/javafx-graphics-11-mac.jar/libjavafx_iio.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    },
```

So next on, I should try to sign the JavaFX jars before putting them into the distribution?

**Comment by berndmoos** [comment]
This is to good to be true: notarization has returned with status "Accepted". Apollo 13 has safely landed, the crew is alive.

![image](https://user-images.githubusercontent.com/13796493/200182015-6df35d37-ae4b-4b79-b5a4-5a2d69b5fe14.png)

![image](https://user-images.githubusercontent.com/13796493/200182052-1ec8082f-62ac-4165-bf19-6c2527edbbea.png)

**Comment by berndmoos** [comment]
I don't think I'll bother with stapling because:

> When you run our software on your machine, Gatekeeper automatically checks to see if the software is valid. If there’s a network connection available, Gatekeeper uses the online Code Directory to look up the ticket and checks it against the software. Should no network is available, Gatekeeper uses the stapled ticket.

**Comment by berndmoos** [comment]
Make Windows signing a separate issue: #347

**Comment by berndmoos** [comment]
For reasons unexplained, the application specific password (NOTARIZATION_PASSWORD) was gone. I generated a new one as described above. However, for more reasons unexplained, "special symbols" are no longer permitted in the identifier. For reasons explained, I therefore boldly named the new application specific password NOTARIZATIONPASSWORD2. It seems to work now. I do not specifically love Apple or so.

**Comment by berndmoos** [comment]
Closed, never to be seen again.
