### ISSUE TITLE
22nd anniversary release

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#214]
Some time between now and April 2021, EXMARaLDA will turn twenty. I would like to make an official release for this occasion, and it shouldn't be total Scheiße. As a first step, maybe everybody here can invest an hour and 
- check whether the newest previews run fine with players playing, splash screens splashing etc.
- look at the open issues and say when one of them is particularly important for whatever reason
I'm writing this in English so that es hört sich professioneller an.
Danke, RSVP bitte in diesem Issue, möglichst bis zum 31.10.2020.
@Herrner: ein kleines 20.-Geburtstags-Gimmick im Partitur-Editor Splash Screen? https://www.creativefabrica.com/wp-content/uploads/2019/03/20th-anniversary-celebration-logo-vector-by-DEEMKA-STUDIO-580x406.jpg

**Comment by berndmoos** [comment]
@Herrner : ich vergesse immer, wo die Logos und SplashScreen-Photoshops sind. Weißt Du's? Könntest Du für den Partitur-Editor-Splash-Screen einen Hinweis "Dulko functionality by Andreas Nolda" hinzufügen?

**Comment by berndmoos** [comment]
@Herrner @hannahedeland @anneferger @daniel-jettka : 

> look at the open issues and say when one of them is particularly important for whatever reason

?

**Comment by Herrner** [comment]
- [ ] #238

**Comment by hannahedeland** [comment]
https://github.com/Exmaralda-Org/exmaralda/issues?q=is%3Aissue+is%3Aopen+iso%2Ftei+in%3Atitle

**Comment by berndmoos** [comment]
It will be a 21st anniversary release. @Herrner : "Dulko functionality by Andreas Nolda" im Splashscreen? It's this one, I think : https://github.com/Exmaralda-Org/exmaralda/blob/master/src/build/misc/graphics/PartiturEditor/splashscreenNEU.psd
I don't have photo shop...

**Comment by Herrner** [comment]
It is in the PSD already... I don't have Photoshop anymore, let's see what I can do...

**Comment by berndmoos** [comment]
> It is in the PSD already... I don't have Photoshop anymore, let's see what I can do...

I can export PNG from PSD with Gimp. Did that for the PE SplashScreen, looks okay.

**Comment by berndmoos** [comment]
More things in SplashScreens:

- Partitur-Editor: the MPI link is not up-to-date anymore (but there is a redirect), could be https://archive.mpi.nl/tla/elan instead
- FOLKER : Replace "FOLKER wird am Programmbereich ... entwickelt" with "FOLKER wird von Thomas Schmidt entwickelt"
- FOLKER: Replace "enthält eine DirectShow-Player-Komponente ... Psycholinguistik" with "enthält Player-Komponenten von ELAN (https://archive.mpi.nl/tla/elan) und BAS (https://www.bas.uni-muenchen.de/)"
- OrthoNormal: Replace "OrthoNormal wird am Programmbereich ... entwickelt" with "OrthoNormal wird von Thomas Schmidt" entwickelt
- EXAKT: "database functionality by HH" - does @hannahedeland still want that?
- COMA: @Herrner ?

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/148410751-93df119d-e643-4d8a-8ba3-e5e7887e87bd.png)
![image](https://user-images.githubusercontent.com/13796493/148410801-69b7d6ba-3e78-428e-878c-94b7736d328a.png)
![image](https://user-images.githubusercontent.com/13796493/148410840-12422ce6-1b2d-4e09-9bfc-45dbc41c2cf1.png)
![image](https://user-images.githubusercontent.com/13796493/148410911-f5990ea7-ca77-4e09-909c-f5ff07ba6656.png)

**Comment by berndmoos** [comment]
Not an issue any more, and also somehow embarrassing, but see milestones.
