### ISSUE TITLE
Tokenize XSL stylesheet for ISO/TEI

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#223]
- as an optional step in importing (see issue #215), but it does not really make sense there
- as a convenient step in exporting because so much more can be done with a tokenized transcript
- the easy way: split PCDATA with a RegEx into sequences of word characters (become `<w>`) and sequences of non-word characters (become `<pc>`)
- the harder way: take into account intervening `<anchor>`s, apply special rules for special things like pauses (@hannahedeland)

**Comment by berndmoos** [comment]
First version produces very hideous output: namespace attributes everywhere, very, very long word-IDs. But it works, sort of.

**Comment by berndmoos** [comment]
@hannahedeland : status?

**Comment by hannahedeland** [comment]
I think this should wait until we have the rest of the ISO/TEI stuff including various segmentation/tokenization options under control, and I won't try to do impossible stuff for now.

**Comment by hannahedeland** [comment]
Or...maybe it would still be good to use this now for non-orthographic conventions within orthographic transcription that are used for non-phonological and/or non-verbal stuff, i.e. things that should go into `<pause>` and `<incident>` elements, or even comments which should be encoded as annotations, and then leave all orthographic text untokenized. As an example from QualiBank data, e.g. `{laughter}` or `...` in the middle of sentences would be recognized as `<incident>` and `<pause>` and then normal tokenization would be possible with less errors for the remaining text. (And this information about transcription conventions could be systematically collected...)

**Comment by berndmoos** [comment]
Closing this. To be reopened when the waters above hell have dropped below 0°C temperature-wise.
