### ISSUE TITLE
TT4J integration for Partitur-Editor

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#228]
TT4J-Anbindung im Partitureditor in einer gegenüber der Dulko-Fassung [3] verbesserten Version mit mehr Spracheinstellungen (nicht nur Deutsch) und TT-Optionen (nicht nur Defaults)

Problem: Das TreeTagger-Stylesheet exb2exb-tag.xsl [4] benötigt für den Aufruf von (2) entweder Saxon-PE (kommerziell) oder Saxon 9.1.0.8 alias Saxon-B (Open Source; war früher mal Teil von EXMARaLDA und wird von Dulko mitgeliefert) [5].

[3]https://hg.sr.ht/~nolda/exmaralda-dulko/browse/src/org/dulko/treetagger/TreeTagger.java
[4] https://hg.sr.ht/~nolda/exmaralda-dulko/browse/share/exb2exb-tag.xsl
[5] http://saxon.sourceforge.net

**Comment by berndmoos** [comment]
Question: the Dulko TreeTagger class uses `System.getenv("TREETAGGER_HOME")`. Is TREETAGGER_HOME reliably set when installing TreeTagger? Or does the user need an option to specify where on the system the tree tagger is installed? Coma and OrthoNormal both use org.exmaralda.tagging.swing.TreeTaggerParametersPanel:

![image](https://user-images.githubusercontent.com/13796493/100849529-fc680380-3482-11eb-9b4d-e0ae3da69c0e.png)

I could add this for the Partitur Editor preferences. Tree tagger home would then be accessible as

`java.util.prefs.Preferences.userRoot().node(TaggingProfiles.PREFERENCES_NODE).get("directory", System.getenv("TREETAGGER_HOME")));`

**Comment by nolda** [comment]
Making this available as a user preference would be very welcome! Setting environment variables proved to be difficult for Dulko users in the past.

**Comment by berndmoos** [comment]
saxon9he.jar is now replaced by saxon.jar in the latest preview

**Comment by berndmoos** [comment]
TreeTagger home directory can now be set vie Edit > Preferences:

![image](https://user-images.githubusercontent.com/13796493/100879028-35b46980-34ab-11eb-82b6-b4564a4b0f13.png)

@nolda : in the Dulko TreeTagger class, instead of `System.getenv("TREETAGGER_HOME")` you should now use `java.util.prefs.Preferences.userRoot().node(TaggingProfiles.PREFERENCES_NODE).get("directory", System.getenv("TREETAGGER_HOME")));`

**Comment by berndmoos** [comment]
Changed Dulko TreeTagger class to work with EXMARaLDA's TreeTagger preferences. If the user specifies a Non-German parameter file, Dulko tagging should now be done with that parameter file (not sure if that's the right idea). Before initialising, the class now checks whether executable and parameter file exist and are readable. This should result in a more helpful error message than the failure message of TreeTagger itself. 

Some more questions @nolda : 
- the class didn't tell the TreeTaggerWrapper where to find the TreeTagger executable. Did it expect the TreeTagger to be in a specific location? Or did it go upwards from the parameter file? Either way, this approach should be more flexible, but I'm not sure if it conflicts with assumptions about paths etc. elsewhere in Dulko. Does it?
- likewise, the class didn't set the parameter file encoding. afaik, most parameter files come in UTF-8 now, but some may remain in other encodings like ISO-8859-1. I am now getting the encoding from the preferences, with "UTF-8" as a fallback. I don't think this is a problem. Is it?

**Comment by nolda** [comment]
> the class didn't tell the TreeTaggerWrapper where to find the TreeTagger executable. Did it expect the TreeTagger to be in a specific location? 

TT4J expects the TreeTagger executable to be in the `bin/` subdirectory of the TreeTagger installation (cf. https://github.com/reckart/tt4j/blob/master/src/main/java/org/annolab/tt4j/DefaultExecutableResolver.java).

**Comment by nolda** [comment]
> I am now getting the encoding from the preferences, with "UTF-8" as a fallback.

Could we make UTF-8 the default in the preferences? As most parameter files are encoded in UTF-8, this might help to avoid erroneous settings.

**Comment by nolda** [comment]
> If the user specifies a Non-German parameter file, Dulko tagging should now be done with that parameter file (not sure if that's the right idea).

Dulko's TreeTagger transformation scenarios are language-agnostic. So, in principle, this is a good thing.

Still, the Dulko tokeniser, which has been developed and tested for German only, might give unexpected results for other languages if the corresponding transformation scenario (`Dulko: word-tier (learner text)`) is run before one of the TreeTagger transformation scenarios (e.g. `Dulko: S-, pos-, and lemma-tiers (learner text)`) as it normally would be. This is why currently Dulko's TreeTagger stylesheet throws an error if the language is not German. I'll better change this to a non-terminating warning.

**Comment by nolda** [comment]
Dulko now supports any language TreeTagger supports in terms of parameter files. The `lang` parameter of the `TreeTagger` constructor is no longer needed and thus removed.
Instead, the language to be used for tagging is determined in the XSLT stylesheets on the basis of the first language used in the speakertable (using German as a default). An error is signaled by `exb2exb-tag.xsl` if the language does not match the parameter file set in the preferences.
In addition, `exb2exb-word.xsl` makes use of TreeTagger's abbreviation file for that language (if any) during tokenisation.

**Comment by nolda** [comment]
Could we extend the TreeTaggerParameterPanel with a field for the path of an abbreviation file (such as `$TREETAGGER_HOME/lib/german-abbreviations`) and its encoding (usually UTF-8)?
That would be useful for Dulko's tokenisation stylesheet `exb2exb-word.xsl` which currently guesses both path and encoding – a guess that may be wrong in non-standard installations.

**Comment by nolda** [comment]
And could we make `utf-8` the default selection for parameter file encoding in the TreeTaggerParameterPanel? Currently, `iso-8859-1` is preselected, which may give rise to erroneous user configurations for current TreeTagger installations.

**Comment by berndmoos** [comment]
- made UTF-8 the default
- added fields for specifying abbreviations file and file encoding

This information can be accessed like so:

```
Preferences preferences = java.util.prefs.Preferences.userRoot().node(TaggingProfiles.PREFERENCES_NODE);
String abbFile = preferences.get("abbreviations-file", ""));
String abbFileEncoding =preferences.get("abbreviations-file-encoding", "utf-8");
```

**Comment by berndmoos** [comment]
Ein User-Wunsch war übrigens mehrfach, die TreeTagger-Option "-no-unknown" setzen zu können, die per Default nicht gesetzt ist. Das könnte man evtl. auch über die Einstellungen lösen.

**Comment by berndmoos** [comment]
And:

`boolean nounknownOption = preferences.getBoolean("nounknown-option", true);`

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/101506151-61d15e00-3975-11eb-9ab2-54dded91c2f3.png)

**Comment by nolda** [comment]
Commit c920755b47c55ce1e75e432b66c0191b95e86a60 introduced a bug in `EditPreferencesDialog.java`, preventing Preferences from being saved:

> Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 35 out of bounds for length 35
>        at org.exmaralda.partitureditor.jexmaraldaswing.EditPreferencesDialog.getValues(EditPreferencesDialog.java:126)

For a quick fix, cf. the following patch:
```
diff --git a/src/org/exmaralda/partitureditor/jexmaraldaswing/EditPreferencesDialog.java b/src/org/exmaralda/partitureditor/jexmaraldaswing/EditPreferencesDialog.java
index c8c06ce..54f23dc 100644
--- a/src/org/exmaralda/partitureditor/jexmaraldaswing/EditPreferencesDialog.java
+++ b/src/org/exmaralda/partitureditor/jexmaraldaswing/EditPreferencesDialog.java
@@ -83,7 +83,7 @@ public class EditPreferencesDialog extends javax.swing.JDialog {
     }
 
     public String[] getValues(){
-        String[] result = new String[35];
+        String[] result = new String[37];
         result[0] = tierFontLabel.getText();
         result[1] = generalPurposeFontLabel.getText();
         result[2] = head2HTMLTextField.getText();
```

**Comment by berndmoos** [comment]
It seems like TT4J is not working with newer versions of TreeTagger :-(

**Comment by berndmoos** [comment]
> It seems like TT4J is not working with newer versions of TreeTagger :-(

Now issue #286 and also https://github.com/reckart/tt4j/issues/35
