### ISSUE TITLE
Integrate Transformation (Scenario)s into the toolbar

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#230]
Einen Toolbar-Button für den Transformations-Dialog oder, besser, ein Drop-down-Menü auf der Toolbar zur Auswahl eines    Transformationsszenarios. Das würde den Nutzern Klicks ersparen.

**Comment by berndmoos** [comment]
As a first step, gave the Transformation Action an ugly (somebody find a better one? it needs to be 24x24) icon and added it to the toolbar. Next on: Think about a dropdown menu

**Comment by nolda** [comment]
Here is a tailor-made icon:
![TransformationScenarios](https://user-images.githubusercontent.com/1439367/101060114-52c26880-358f-11eb-83ce-30be95e9fedb.gif)

**Comment by nolda** [comment]
+1 for a drop-down menu

**Comment by berndmoos** [comment]
The dropdown takes a little bit of space in the toolbar, so displaying it is now an option in "Edit > Preferences > Menus & Toolbars)". 

![image](https://user-images.githubusercontent.com/13796493/101615120-0bfcc480-3a0e-11eb-8824-2f3ec6461692.png)

It's there, and it seems to work. 

![image](https://user-images.githubusercontent.com/13796493/101615076-fe473f00-3a0d-11eb-9091-eb7b230afed8.png)

The code for it is quite distributed in a not very elegant manner...
