### ISSUE TITLE
Better error handling in XSL Transformations

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#233]
XSLT-Fehlermeldungen (<xsl:message terminate="yes">) durchreichen statt der gegenwärtigen kryptischen Fehlermeldung "Processing terminated by xsl:message at line ... in ..." (s. Screenshot und Logdatei [6]). Möglicherweise ist das ein Saxon-Problem [7].

![image](https://user-images.githubusercontent.com/13796493/100606792-41b4f580-330a-11eb-9a93-9d6f9b443acb.png)

[6] aus EXMARaLDA-Partitur-Editor.log:
    transformationAction
    Error: There is no reference tier for the $zh-number value "1".
    net.sf.saxon.instruct.TerminationException: Processing terminated
    by xsl:message at line 43 in exb2exb-tiers.xsl at
    net.sf.saxon.instruct.Message.processLeavingTail(Message.java:222)

[7] https://stackoverflow.com/q/4695489

**Comment by berndmoos** [comment]
@nolda : can I have a test case, i.e. a transformation that will produce an `<xsl:message terminate="yes">`?

**Comment by nolda** [comment]
Run any Dulko transformation scenario with a `Requires existing … tiers.` in the description without generating those tiers in the first place. E.g. run "Dulko: Diff-tier (learner text)" on a blank transcription. This should throw an error with the message `Error: There is no tier to compare with the reference tier.`, generated by a `<xsl:message terminate="yes">` in the stylesheet `exb2exb-diff.xsl`.

**Comment by daniel-jettka** [comment]
Might not really help, but for Flextext Import in PE (File > Import... > Flex XML File or via INEL custom menu) errors during XSLT transformation are transferred into a pop-up box in PE. The errors are however triggered by XPath's `error()` and not `xsl:message`

Class: https://github.com/Exmaralda-Org/exmaralda/blob/master/src/org/exmaralda/partitureditor/jexmaralda/convert/FlexTextConverter.java
XSLT: https://github.com/Exmaralda-Org/exmaralda/blob/e3486daafc994ab1c216ae9e625fccbe131a6b6b/src/org/exmaralda/partitureditor/jexmaralda/xsl/flextext2exb.xsl

Apart from that capturing xsl:message would be great of course.
https://stackoverflow.com/questions/33349610/xsltmessage-in-saxon-9-4-vs-saxon-9-6

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/101599616-53795580-39fa-11eb-9818-e83930736e1f.png)
