### ISSUE TITLE
Make a proper licence statement

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#239]
... in a licence.txt with the code and in the copyright statement of InnoSetup. GPL 2.0 (compare https://hg.sr.ht/~nolda/exmaralda-dulko/browse/licenses/LICENSE) is the best candidate.

**Comment by berndmoos** [comment]
Done that: License statement in META-INF, changed the copyright statement.

**Comment by nolda** [comment]
`META-INF/license.txt` (GPL 2) and `META-INF/license_de.txt` (GPL 3, German translation) are incompatible.
