### ISSUE TITLE
Regression: relative @href in XSLT stylesheets not found

### ISSUE THREAD

**Issue by nolda** [Exmaralda-Org/exmaralda#243]
Support for relative @href in XSLT stylesheets (added in #138) is not present in the current Windows preview. This prevents the new Dulko stylesheets from working, which make extensive use of relative @href's (cf. the attached
[EXMARaLDA_Partitur-Editor.log](https://github.com/Exmaralda-Org/exmaralda/files/5635567/EXMARaLDA_Partitur-Editor.log)). With the (not up-to-date) Linux preview, the Dulko stylesheets do work as before.

**Comment by berndmoos** [comment]
Either this is a bug in saxon9 which is not present in saxon9he (I don't think so), or it has to do with the setting of the URI resolver in org.exmaralda.partitureditor.jexmaralda.convert.StylesheetFactory (I think so). The difference would then be that URI resolving works for external, but not for internal stylesheets. I'll look into it. 

https://twitter.com/AGDIDS/status/1334105587769090058

**Comment by nolda** [comment]
I can confirm that the bug is not related to saxon9. The error remains the same if saxon9 is replaced by saxon9he:
```
transformationAction
Error on line 10 column 38 of exb2exb-txtword-format.xsl:
  XTSE0165: I/O error reported by XML parser processing exb2exb-word.xsl: C:\Program
  Files\EXMARaLDA\exb2exb-word.xsl (The system cannot find the file specified)
Dec 03, 2020 2:37:39 PM org.exmaralda.partitureditor.partiture.transcriptionActions.TransformationAction transformation
SEVERE: null
javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: I/O error reported by XML parser processing exb2exb-word.xsl: C:\Program Files\EXMARaLDA\exb2exb-word.xsl (The system cannot find the file specified)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:155)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTransformer(SaxonTransformerFactory.java:108)
	at org.exmaralda.partitureditor.jexmaralda.convert.StylesheetFactory.applyInternalStylesheetToString(StylesheetFactory.java:75)
```
The XSLT stylesheet `exb2exb-word.xsl` is imported by a relative `@href` from `exb2exb-txtword-format.xsl` and resides in the same source directory as the latter (i.e. `src/org/exmaralda/partitureditor/jexmaralda/xsl/dulko/`).

**Comment by nolda** [comment]
I also can confirm that the current setup works with the old `StylesheetFactory`. As a test-case, I've added `org/exmaralda/partitureditor/jexmaralda/xsl/dulko/` and `org/exmaralda/partitureditor/partiture/transcriptionActions/TransformationScenarios.xml` to `lib/EXMARaLDA.jar` in the outdated Linux preview. After overwriting `saxon9he.jar` with `saxon9.jar`, the Dulko transformation scenarios work as expected.

**Comment by berndmoos** [comment]
> I also can confirm that the current setup works with the old StylesheetFactory. 

Then it must be the change from issue #229 : the variant *with* parameters tries to set a custom URI resolver while the (old) variant without parameters does not. Seems like a good idea to take out the attempt to set the URI resolver. Did that, new preview under way. Please test.

**Comment by nolda** [comment]
Now it works. Thanks for the quick resolution!

**Comment by berndmoos** [comment]
Close dis!
