### ISSUE TITLE
Icons and Splashscreens

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#255]
I have icons for Win and MAC OS and splashscreens as pngs. I need icons as PNGs (for Linux) and splashscreens as photoshop files (for editing, though I don't have photoshop...). I can't find them on Git. Can you purrem there? Best place may be a new folder under "templates".

**Comment by Herrner** [comment]
`templates` being `EXMARaLDA_NetBeans_Project/templates/`?

**Comment by berndmoos** [comment]
Yes

Kai Woerner <notifications@github.com> schrieb am Fr. 11. Dez. 2020 um
14:22:

**Comment by berndmoos** [comment]
under ../graphics and there are many, many of them
