### ISSUE TITLE
MAC OS 11 (Big Sur) and/or MAC with M1 processor

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#256]
... something fishy, of course. 

This (from Ticket#2021010200000035)...

![image](https://user-images.githubusercontent.com/13796493/103526002-6f98d700-4e80-11eb-80a8-0a395643a35c.png)

... looks weird. Need two new MACs.

**Comment by berndmoos** [comment]
From a Big Sur M1 log file:

```
************* INFO **************
Date : Mon Jan 04 11:17:00 CET 2021
Operating system : Mac OS X
Operating system architecture : x86_64
OS version : 10.16
JRE version : 14
JRE vendor : Oracle Corporation
JVM version (specification/implementation) : 14 / 14+36-1461
org.sfb538.exmaralda.PartiturEditor.PlayerType: AVF-Player
```

**Comment by berndmoos** [comment]
... and then this, from Ticket#2021010400000077:

![image](https://user-images.githubusercontent.com/13796493/103734713-ddfaa800-4fec-11eb-85fa-a657f48223c5.png)

See also issue #205

**Comment by berndmoos** [comment]
Forget the last entry -- this looks like the user tried to install the "official", not the preview version.

**Comment by Grace3698** [comment]
Hello have you find the results 
i have the same problem

**Comment by berndmoos** [comment]
Testing on a MacMini with MAC OS 11 and M1 chip:
- Download latest preview: MAC OS wants to install/activate "Rosetta". With Rosetta installed/activated, the PE works like a charm. It says, it is running under MAC OS 10.16 with architecture x86_64 (not ARM 64-bit), but "About this MAC" says it is running MAC OS 11.2.3
- There is a JDK 15 by Zulu: https://www.azul.com/downloads/zulu-community/?version=java-15-mts&os=macos&architecture=arm-64-bit&package=jdk (Note that "architecture" needs to be "ARM 64-bit") which can be installed without problems
- Apache NetBeans (12.2) also wants to run via Rosetta. It can't find the Zulu SDK

==> For the time being, tell users to install/activate Rosetta -- meanwhile, either wait for Apache NetBeans to make a native M1 version, or setup a build process without NetBeans

**Comment by Herrner** [comment]
> Testing on a MacMini with MAC OS 11 and M1 chip:
> 
> * Download latest preview: MAC OS wants to install/activate "Rosetta". With Rosetta installed/activated, the PE works like a charm. It says, it is running under MAC OS 10.16 with architecture x86_64 (not ARM 64-bit), but "About this MAC" says it is running MAC OS 11.2.3
> * There is a JDK 15 by Zulu: https://www.azul.com/downloads/zulu-community/?version=java-15-mts&os=macos&architecture=arm-64-bit&package=jdk (Note that "architecture" needs to be "ARM 64-bit") which can be installed without problems
> * Apache NetBeans (12.2) also wants to run via Rosetta. It can't find the Zulu SDK
> 
> ==> For the time being, tell users to install/activate Rosetta -- meanwhile, either wait for Apache NetBeans to make a native M1 version, or setup a build process without NetBeans

For clarification: ARM64m X86_64 and x64 are the same architecture, as are ARM64 and AArch64.
There are several Java VMs for ARM64 and [precompiled NetBeans versions](https://pkgs.org/download/netbeans) for ARM64.

**Comment by berndmoos** [comment]
OpenJDK 17 (September 2021) officially supports M1 on the MAC : https://jdk.java.net/17/

**Comment by berndmoos** [comment]
No reason not to build with OpenJDK17 on the MAC in general (i.e. also for Intel), or is there? Need to test, still have a M1 Mac without a monitor, and soon a new one.

**Comment by berndmoos** [comment]
Did a build with OpenJDK17 on a M1-MAC. Needed to integrate the native ELAN player code for M1 (so, again, we will have two versions of each tool for the MAC)... New problem is: I do not have an x86 MAC anymore... Anyway, the build is succesful, and the AVF player is playing audio and video. Debug info is saying: 

Operating system architecture: aarch64
OS version: 12.1
JRE version 17.0.2.
JRE vendor: Azul Systems, Inc.
JVM version (specification/implementation): 17 / 17.02+8-LTS

**Comment by berndmoos** [comment]
:-( That's what I get for the application packaged with jpackage:

`The application /Users/thomasschmidt/Dropbox/Mac/Desktop/EXMARaLDA_Build/PartiturEditor_13_64/PartiturEditor.app cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x60000244a610 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}`

**Comment by berndmoos** [comment]
Removed the "Remove faulty signatures" part in the ant script. Now the packaged application starts. Hooray.

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/154508692-cf34c9b8-8046-4f39-bbf1-b51c153fa474.png)


Now I'm getting Unsatisfied link errors, but it's looking for the native libs in the wrong place -- the folder "Contents" is missing in the path, so I put it there, now player plays.

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/154583863-2b090d0d-cac1-4564-9fa9-55c9e7c03972.png)

**Comment by berndmoos** [comment]
Not starting... Maybe this?

https://developer.apple.com/forums/thread/666611?page=5

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/189493128-8751ccd8-fa70-4851-82c2-36f02be6b27a.png)

**Comment by berndmoos** [comment]
Setup:

* Product Version: Apache NetBeans IDE 15
* Java: 17.0.5; OpenJDK 64-Bit Server VM 17.0.5+8
* Runtime: OpenJDK Runtime Environment 17.0.5+8
* System: Mac OS X version 13.0 running on aarch64; UTF-8; en_DE (nb)

**Working from NetBeans: PE starts, AVF player okay, BAS player okay, JavaFX player not:**

```
INFO: JFXMediaPlayer URL: file:////Users/thomasschmidt/Desktop/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-4.mp4
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/thomasschmidt/.openjfx/cache/11/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/thomasschmidt/.openjfx/cache/11/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:205)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:185)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:157)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:68)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:50)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/thomasschmidt/.openjfx/cache/11/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/thomasschmidt/.openjfx/cache/11/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:205)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:185)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:157)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:234)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:234)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by berndmoos** [comment]
Very helpful error message when trying to import certificate into keychain:

![image](https://user-images.githubusercontent.com/13796493/199668605-39ca78b8-0a9f-4de1-8476-9b55a54c5043.png)

**Comment by berndmoos** [comment]
Certificate imported, ant script adapted. Something wrong with libsendpraat.dylib?

```
mac_DMGS_jpackage_EXPERIMENTAL:
jdk.jpackage.internal.PackagerException: java.io.IOException: Command [/usr/bin/codesign, -s, Developer ID Application: Thomas Schmidt (YXGNP3T9KU), -vvvv, --timestamp, --options, runtime, --prefix, org.exmaralda.folker.application., /var/folders/c4/t8x0y7r110b14fv_33hfwrg80000gn/T/jdk.jpackage2747023684550917046/images/image-1688218725490960311/FOLKER.app/Contents/app/native/libsendpraat.dylib] exited with 1 code
Result: 1
jdk.jpackage.internal.PackagerException: java.io.IOException: Command [/usr/bin/codesign, -s, Developer ID Application: Thomas Schmidt (YXGNP3T9KU), -vvvv, --timestamp, --options, runtime, --prefix, org.exmaralda.partitureditor.partiture., /var/folders/c4/t8x0y7r110b14fv_33hfwrg80000gn/T/jdk.jpackage9098022082872879013/images/image-9417806852640117568/PartiturEditor.app/Contents/app/native/libsendpraat.dylib] exited with 1 code
Result: 1
jdk.jpackage.internal.PackagerException: java.io.IOException: Command [/usr/bin/codesign, -s, Developer ID Application: Thomas Schmidt (YXGNP3T9KU), -vvvv, --timestamp, --options, runtime, --prefix, org.exmaralda.coma.launcher., /var/folders/c4/t8x0y7r110b14fv_33hfwrg80000gn/T/jdk.jpackage9854257742822035447/images/image-8385736079234906809/Coma.app/Contents/app/native/libsendpraat.dylib] exited with 1 code
Result: 1
jdk.jpackage.internal.PackagerException: java.io.IOException: Command [/usr/bin/codesign, -s, Developer ID Application: Thomas Schmidt (YXGNP3T9KU), -vvvv, --timestamp, --options, runtime, --prefix, org.exmaralda.exakt.exmaraldaSearch.swing., /var/folders/c4/t8x0y7r110b14fv_33hfwrg80000gn/T/jdk.jpackage4847339168640719644/images/image-5170121578017567413/EXAKT.app/Contents/app/native/libsendpraat.dylib] exited with 1 code
Result: 1
jdk.jpackage.internal.PackagerException: java.io.IOException: Command [/usr/bin/codesign, -s, Developer ID Application: Thomas Schmidt (YXGNP3T9KU), -vvvv, --timestamp, --options, runtime, --prefix, org.exmaralda.orthonormal.application., /var/folders/c4/t8x0y7r110b14fv_33hfwrg80000gn/T/jdk.jpackage3803936301754948278/images/image-2002320326294340162/OrthoNormal.app/Contents/app/native/libsendpraat.dylib] exited with 1 code
Result: 1
jdk.jpackage.internal.PackagerException: java.io.IOException: Command [/usr/bin/codesign, -s, Developer ID Application: Thomas Schmidt (YXGNP3T9KU), -vvvv, --timestamp, --options, runtime, --prefix, org.exmaralda.tei.swing., /var/folders/c4/t8x0y7r110b14fv_33hfwrg80000gn/T/jdk.jpackage14573720421559648481/images/image-5627985378039778968/TeiDrop.app/Contents/app/native/libsendpraat.dylib] exited with 1 code
Result: 1
```

**Comment by berndmoos** [comment]
Something wrong with **all** dylibs. Removing their signature before calling jpackage makes no difference.

**Comment by berndmoos** [comment]
JavaFXPlayer is okay after replacing javafx--...mac.jar with javafx-...-mac-aarch64.jar (the latter taken from the ELAN distribution - they are for JDK 18, but that does not seem to do any harm).

**Comment by berndmoos** [comment]
Managed to sign (?), upload, download and start PartiturEditor on a M1 MAC. This is from the log:

```
************* INFO **************
Date : Fri Nov 04 18:08:39 CET 2022
Operating system : Mac OS X
Operating system architecture : aarch64
OS version : 13.0
JRE version : 17.0.5
JRE vendor : Eclipse Adoptium
JVM version (specification/implementation) : 17 / 17.0.5+8
```
The JavaFX problem is back, but AVF player opens Beckhams all right.

@Herrner (where is @wuddel?) : can you test and share things known?

https://exmaralda.org/files/prevDL/experimental.html

**Comment by Herrner** [comment]
I can also play the Beckhams alright. This is totally minor, but the Folder you drag the app to is titled `/Applications` (with a slash) - it works, tho. 
<img width="220" alt="image" src="https://user-images.githubusercontent.com/2045460/200066310-d8641740-03e1-4d52-bfb2-288bae6edef0.png">

**Comment by Herrner** [comment]
Also Coma works like a charm (of course...), but looks odd. 
<img width="249" alt="image" src="https://user-images.githubusercontent.com/2045460/200067009-a3750ebd-ce04-4544-8529-a3604a9a8113.png">
I'm wondering how these bitmap graphics are actually still readable with these ultra high resolutions.

**Comment by Herrner** [comment]
I'm not so sure about the signing. I get the "can't look inside the package" for all .dmgs and have to context-click them to run.

**Comment by berndmoos** [comment]
> I get the "can't look inside the package" for all .dmgs

What's that? Is that when you try to open the dmg or when you try to launch the application? 
This is what I get when trying to open the application without right mouseclick:

![image](https://user-images.githubusercontent.com/13796493/200142867-4ee008fb-8161-431f-ace0-99d1f9f456d2.png)

Coma will be beautiful as before when we adjust the JButton sizes ;-)

**Comment by berndmoos** [comment]
I think the "malicious software" message will only go away after notarizing. Signing is necessary to open it in the first place, and as a prerequiste for notarizing. Not there yet...

**Comment by berndmoos** [comment]
> The JavaFX problem is back, but AVF player opens Beckhams all right.

The JavaFX problem is solved (I think): The built version still had the Non-M1-Jars. Clean & Build remedied that.

**Comment by berndmoos** [comment]
Reports for the current distribution:
- okay on @Herrner 's computer -- M1 / MAC OS 13.0
- okay on @berndmoos computer -- M1 / MAC OS 13.0
- okay on @berndmoos other computer -- Intel / MAC OS 12.6
- okay on Han's computer -- M1 / MAC OS ??
- okay on Latif's computer -- probably M1 / MAC OS 13.0
- fail on Anthea A.'s computer -- M1 / MAC OS 12.5.1

<img width="423" alt="Bildschirmfoto 2022-11-07 um 13 40 23" src="https://user-images.githubusercontent.com/13796493/200785510-618204d0-8920-4b79-8810-18fd126d23f2.png">

- now okay on Anthea's computer -- M1 / MAC OS 12.5.1

```
************* INFO **************
Date : Wed Nov 09 13:08:06 CET 2022
Operating system : Mac OS X
Operating system architecture : x86_64
OS version : 12.5.1
JRE version : 17.0.5
JRE vendor : Eclipse Adoptium
JVM version (specification/implementation) : 17 / 17.0.5+8

```
That is weird because it is definitely a M1 Mac. Maybe that is what happens with Rosetta?

**Comment by berndmoos** [comment]
Yay, I think
