### ISSUE TITLE
Revise Weblicht function

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#262]
* .. in theory: could use any chain starting with PE, could go back to PE via ISO/TEI import
* .. in practice: EXB2ISOTEI web service would have to be updated, right now it is not even running (https://corpora.uni-hamburg.de/apps/HZSK-CLARIN-Services-0.9/exb2isoTeiConverter) which is a downdate, more like, man, just sayin

**Comment by berndmoos** [comment]
The HZSK webservice is fixed (not updated), so I'm trying. Calling a standard "all-in-one-chain" on a Hamatac transcript gives 

`Input profile is incompatible with the chain.
`
This may be due to TCF 4 vs. 5 see #212

**Comment by berndmoos** [comment]
> This may be due to TCF 4 vs. 5 see #212

No, it is not. TCF 4 works, it just needs a chain that starts with tokenized input.

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/110511241-50c6f300-8104-11eb-87fa-406b2094ea48.png)

:-o

**Comment by hannahedeland** [comment]
Some minor things:
* in the WebLicht Parameters dialogue box, Output section, the Browse... doesn’t start from the last used(?) directory for HTML (but for the others)
* it would be nice if more parameters than the API key could be remembered between calls
