### ISSUE TITLE
Brown noise generator fails in some cirumstances with invalid min/max

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#269]
Exception is thrown at org.exmaralda.masker.Masker.getMask(Masker.java:194) : 

`
BrownNoiseGenerator brownNoiseGenerator = new BrownNoiseGenerator(lowerLimit,upperLimit,(upperLimit - lowerLimit) / 20,0.02,currentValue);
`

[[Code](https://github.com/Exmaralda-Org/exmaralda/blob/455670e044aa54b50845163c5e4ff9854c69d3ca/src/org/exmaralda/masker/Masker.java#L194)]

**Comment by wuddel** [comment]
This may happen, e.g. when the signal is flat (zero). Then the upperLimit = lowerLimit, which means their difference is zero. When devided by something, this may create the error.
I guess, as you suggest, we can get around this by simply creating the condition:
if (upperLimit <= lowerLimit) {lowerLimit = upperLimit - 0.01}

**Comment by berndmoos** [comment]
Did that, seems to work.

**Comment by berndmoos** [comment]
There is another problem at line 144 in Masker.java:

```
java.lang.NullPointerException
	at org.exmaralda.masker.Masker.getMask(Masker.java:182)
	at org.exmaralda.masker.Masker.maskFrames(Masker.java:144)
	at org.exmaralda.masker.Masker.mask(Masker.java:80)
	at org.exmaralda.folker.application.ApplicationControl$5.run(ApplicationControl.java:3124)

```
The array `lastBufferValues` can be null if it hasn't been initiated before, this seems to be a boundary condition. Might help to check if it has been initiated.

**Comment by wuddel** [comment]
This seems to happen, when the event to be masked is identical to the first event in the transcription. 
As the double array `lastBufferValues` is initiated within the method copyFrames (following the wrong assumption that a mask event may only occur somewhere within the transcription), the array `lastBufferValues` is not initialized, yet. In order to do so, I suggest to take the first value (values, if more than one channel) of the wav-file as the initialisation.

We coud put at line 64 of Masker.java:
```
// Create a buffer of 1 frame
double[] lastBufferValues = new double[1 * numChannels];

do {
   // Read frames into buffer
   framesRead = wavFileIn.readFrames(lastBufferValues, 1);
}
```
Can this work?

**Comment by berndmoos** [comment]
> Can this work?

No, I don't think, because this makes `lastBufferValues `a local variable and it will get intitiated in each call of the methode. Put this code into the constructor instead.

**Comment by wuddel** [comment]
Good idea! Thanks for the hint. 
With the new change, the masking now also works at the boundary condition.

**Comment by berndmoos** [comment]
This has been fixed.
