### ISSUE TITLE
Focus accents cut words in selection of suggested normalisations

### ISSUE THREAD

**Issue by wuddel** [Exmaralda-Org/exmaralda#271]
In OrthoNormal: If the original FLK-Transcription contains focus accents, i.e. words that are spelled with capital letters somewhere in the word, after auto-normalisation, the suggestions for normalised words do not contain the capital letters in small letters. For example "geSICHtet" becomes "getet"; the "sich" disappears.

**Comment by berndmoos** [comment]
`WordUtilities.getWordText(wordElement)` instead of `wordElement.getText()` at appropriate places in the code

**Comment by wuddel** [comment]
Thanks a lot for fixing the bug. The new preview works now without problems. Merely at the installation summary, the bugfix #271 is not mentioned, yet.
