### ISSUE TITLE
fix csv export in exakt

### ISSUE THREAD

**Issue by TimmLehmberg** [Exmaralda-Org/exmaralda#277]
when saving a concordance as csv with exakt, entries with empty (left and right) context are not written properly

[wie.csv](https://github.com/Exmaralda-Org/exmaralda/files/6961493/wie.csv)
![wie](https://user-images.githubusercontent.com/15217948/128863675-ee3998ca-511f-42a6-98ea-6b51506720ee.png)

**Comment by berndmoos** [comment]
@TimmLehmberg : Can I have an example of what "not properly" means?

**Comment by berndmoos** [comment]
> @TimmLehmberg : Can I have an example of what "not properly" means?

Yes I can: if the left context is empty, the line ends after the entry for the speaker, like so:

Janis_Hamit/MT_280410_Hamit/MT_280410_Hamit_s.exs,(//segmentation[@name='SpeakerContribution_Event']/ts)[29],MT_280410_Hamit,Ham

**Comment by berndmoos** [comment]
The problem is in the XSLT in Jettonski style:

https://github.com/Exmaralda-Org/exmaralda/blob/9521c304657af204ab23d215a3283991ee3f10e6/src/org/exmaralda/exakt/resources/SearchResult2CSV.xsl

What the heck does `','[not($result='')]` do or mean???

**Comment by berndmoos** [comment]
@TimmLehmberg : methinks I fixed it. Can somebody who is actually working with the CSV export please check (preview only for Windows)

**Comment by berndmoos** [comment]
Somebody can't or nobody is working with it.
