### ISSUE TITLE
Make and test MAC OS dmgs

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#29]
Made them, they are in the dropbox folder. 

Test on MAC OS 10.10.5 (Yosemite, Thomas@IDS)
* Partitur-Editor starts, can display Rudi with video
* EXAKT starts, can search for "cheese", audio will play
* COMA starts, can open files

**Comment by berndmoos** [comment]
@Herrner Test on MAC OS Sierra?

**Comment by berndmoos** [comment]
We will also need distributions for Java 1.8 or shit will hit fan.

**Comment by berndmoos** [comment]
Now 5 new distributions - PE, Coma, EXAKT, FOLKER, OrthoNormal for MAC OS with Oracle Java. May the Lord protect us!
![image](https://cloud.githubusercontent.com/assets/13796493/23506851/9134d4ec-ff4a-11e6-9553-84d72554e223.png)

**Comment by berndmoos** [comment]
The "notes for installation" need to explain the difference between the different distributions, the  "Audio & Video support" document likewise

**Comment by berndmoos** [comment]
Remaining problem: https://support.clarin-d.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=2912 ?

**Comment by Herrner** [comment]
remaining problems should be added as new tickets for >1.6.
