### ISSUE TITLE
New version of demo corpus

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#32]
Should have MPEG-1 videos with the recommended specifications...

**Comment by berndmoos** [comment]
Should also have up-to-date ISO/TEI exports. Current version is on: S:/.../Korpora/HZSK/EXMARaLDA-Demokorpus. New version can go into repository, but needs copy for EXAKT remote corpus

**Comment by berndmoos** [comment]
related to #155 and #48

**Comment by berndmoos** [comment]
@hannahedeland hat eine verbesserte Kopie auf den AGD-Workspace gelegt.
Es gibt auch eine Kopie einer älteren Version im "Langzeitspeicher" (dort nur zu Testzwecken): https://s3-uhh.lzs.uni-hamburg.de/ban4152-inel/DemoCorpus/EXMARaLDA_DemoKorpus.coma

**Comment by berndmoos** [comment]
New version (copy on AGD workspace as the starting point) goes to UHH-Amazon-Langzeitspeicher. 
Prefix will be gwiss-exmaralda.
To do:
- audio and video in AGD standard (MPEG-1 can stay, but we need MPEG-4 also)
- maybe other things

**Comment by berndmoos** [comment]
> audio and video in AGD standard (MPEG-1 can stay, but we need MPEG-4 also)

JI thinks he can do this until November 6th (2020)

**Comment by RunaRagnarok** [comment]
Ronia bereitet das Demokorpus gerade auf und sie erstellt auch mpeg-4 wo sie fehlen. Sie wird diese oder nächste Woche irgendwann fertig sein

**Comment by berndmoos** [comment]
> Ronia bereitet das Demokorpus gerade auf und sie erstellt auch mpeg-4 wo sie fehlen. Sie wird diese oder nächste Woche irgendwann fertig sein

Sorry, das war mir nicht klar. Die MPEG-4s werden jetzt am IDS im Medienstudio gemacht, das hat den Vorteil, dass sie dann ganz genau so sind wie alles andere am AGD. Braucht @RunaRagnarok also nicht zu machen. Wofür ist denn diese Aufbereitung gedacht? Und was wird da gemacht?

**Comment by RunaRagnarok** [comment]
Ok, dann sag ich Ronia, sie braucht die MPEG-4 nicht erstellen. Könnt ihr die teilen, wenn sie fertig sind, dass sie in der neuen Version unterkommen?
Es werden zum Beispiel die Metadaten vereinheitlich (z. B. occcupation oder ungewollte Leerzeichen), teilweise machen die oggs Probleme (z. B. in Latoya Jackson mit der Alignierung), die werden dann überall rausgenommen, neue html Visualisierungen, solche Sachen.

LG Heidi

**Comment by berndmoos** [comment]
Ah ich dachte: @RunaRagnarok = Ronia.

Klar können wir die MPEG-4s teilen. Wir sollten irgendwie anstreben, am Schluss dann *eine* verbesserte Version des Demokorpus zu haben. Ich brauche das erstens für dieses Issue, zweitens für die weitere "Vermarktung" von EXMARaLDA. Wofür braucht Ihr das?

**Comment by RunaRagnarok** [comment]
Ja das wäre gut. Der Grundgedanke war für Schulungen, dass man es einmal ordentlich hat und sich seine Fehler selbst einbauen kann. Und Ronia hatte gerade Zeit dafür. Ich teile es mit dir wenn es fertig ist, vielleicht hast du ja dann noch Anmerkungen dazu.

**Comment by Herrner** [comment]
https://www.fdr.uni-hamburg.de/record/8364

Maybe we could add a useful previewable file for 1.2...

**Comment by berndmoos** [comment]
Close dis. The demo corpus is the demo corpus is the demo corpus.
