### ISSUE TITLE
Where to upload previews etc.?

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#34]
Previews need an upload address compatible with the new website structure (currently: remotedir="/exmaralda/wp-content/themes/exmaralda/assets/files/prevDL"). Changes.html must also be uploaded and linked from the downloads page. Now that we don't have the download shortcut on the homepage any more, can we make disk images for individual apps again (instead of one giant dmg for all)? The things knower may know these things.

**Comment by Herrner** [comment]
### Previews: 
Upload to `www.exmaralda.org/files/prevDL`
German description: `www.exmaralda.org/files/prevDL/prev_de.html`
English description: `www.exmaralda.org/files/prevDL/prev_en.html`

### Release Version:
Upload to `www.exmaralda.org/files/officialDL/`
German description: `www.exmaralda.org/files/officialDL/official_de.html`
English description: `www.exmaralda.org/files/officialDL/official_en.html`
