### ISSUE TITLE
"Add annotation" function doesn't work with pos annotation tiers (that can be null)

### ISSUE THREAD

**Issue by anneferger** [Exmaralda-Org/exmaralda#36]
The tier can be null for pos tags, so it can't be found by the "add annotation" function. It can be found with the "AnnotationSearchResult" . 

In the method `SearchResultList addAnnotationAsAnalysis` the possibility
`if (tiers.size()==0){ ... } ` must be added.

**Comment by berndmoos** [comment]
Fixed it. Maybe. Is very ugly (org.exmaralda.exakt.search.SearchResultList: lines 369ff)
