### ISSUE TITLE
EXMARaLDA Splash-Screen Update

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#37]
"Contains player components from ELAN [...]" should become 
"Contains player components from ELAN [...] and BAS (...)"

Ich habe leider kein Photoshop mehr....

**Comment by Herrner** [comment]
Some time in the future someone has to explain git to me... again!

**Comment by berndmoos** [comment]
We need another update:

* TEIDrop version should be 1.0 now
* OrthoNormal version should be 1.0 now

**Comment by EXMARaLDA** [comment]
Soll ich? Soll ich?


________________________________
Von: Thomas Schmidt ***@***.***>
Gesendet: Sonntag, 6. November 2022 18:25:19
An: Exmaralda-Org/exmaralda
Cc: Subscribed
Betreff: Re: [Exmaralda-Org/exmaralda] EXMARaLDA Splash-Screen Update (#37)


We need another update:

  *   TEIDrop version should be 1.0 now
  *   OrthoNormal version should be 1.0 now

**Comment by berndmoos** [comment]
Yes, please splash away.

**Comment by berndmoos** [comment]
This is so 2010s, so I'm closing it.
