### ISSUE TITLE
Check vlc4j as an option for the media player

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#45]
... mainly for Liniux, but maybe also for MAC OS + Java 1.8, and why not for Windows?

http://capricasoftware.co.uk/#/projects/vlcj

**Comment by Herrner** [comment]
Das .jar schleppen wir doch schon seit mindestens 2013 mit - wer hat denn damit was gemacht?

**Comment by berndmoos** [comment]
Ich war's, ich war's!

**Comment by berndmoos** [comment]
Give up on this
