### ISSUE TITLE
Enable HTTPS connections

### ISSUE THREAD

**Issue by hannahedeland** [Exmaralda-Org/exmaralda#48]

**Comment by berndmoos** [comment]
Related to #155

**Comment by berndmoos** [comment]
Es gibt auch eine Kopie im "Langzeitspeicher": https://s3-uhh.lzs.uni-hamburg.de/ban4152-inel/DemoCorpus/EXMARaLDA_DemoKorpus.coma

**Comment by berndmoos** [comment]
There doesn't seem to be a problem with https, at least for corpora without authentication, cf.:

https://s3-uhh.lzs.uni-hamburg.de/ban4152-inel/DemoCorpus/EXMARaLDA_DemoKorpus.coma

Since we don't have remote corpora **with** authentication any more (or do we?), this issue is becoming a non-issue

**Comment by hannahedeland** [comment]
yes, if only the demo corpus and the INEL corpora will be used as remote corpora there is no need for https authentication for now
