### ISSUE TITLE
Repository Catalogue

### ISSUE THREAD

**Issue by hannahedeland** [Exmaralda-Org/exmaralda#49]
There needs to be a list of accessible repository corpora for EXAKT, and preferrably not a new one.

**Comment by daniel-jettka** [comment]
https://lab.multilingua.uni-hamburg.de/redmine/projects/infrastruktur/wiki/Resource_Index_Search_Service_(RISearch)

**Comment by daniel-jettka** [comment]
Corpora in repository are still not readable by EXAKT because the Coma file does not contain references to the datastreams for transcripts.

**Comment by hannahedeland** [comment]
will not be implemented for the HZSK repository
