### ISSUE TITLE
CheckVersionAction > BrowserLauncher problem on Linux

### ISSUE THREAD

**Issue by hannahedeland** [Exmaralda-Org/exmaralda#59]
On Linux,:
"cannot run program "Netscape""

**Comment by hannahedeland** [comment]
...and in index.php, we'll need ../en/release-version/ since en_downloads is gone?

**Comment by hannahedeland** [comment]
??? here too, Chrome cache clean, registry manually cleaned up after deinstallation (got rid of my very special Cannot find SunJMF error message), but still there. Probably it's just me. For Linux it happens to others though.

**Comment by berndmoos** [comment]
http://askubuntu.com/questions/8252/how-to-launch-default-web-browser-from-the-terminal

**Comment by berndmoos** [comment]
That should be gone, since the browser launcher has been replaced by a standard JDK desktop.* call. Need to check,

**Comment by hannahedeland** [comment]
Still get an IO error on LM 20.2 when P-E tries to run netscape - maybe it's just me ;) - but Coma opens my browser (Firefox) to show the EXMARaLDA website.

**Comment by berndmoos** [comment]
@hannahedeland : log file?

**Comment by berndmoos** [comment]
Oops. There was a "BrowserLauncher" left. Replaced it with the desktop.*call. Should work in the next preview. 

Then again: Who needs check version anyway? It doesn't really give a sensible answer: http://www.exmaralda.org/update/index.php?program=partitureditor&version=1.7&java=14&os=Windows+10&osversion=10.0

**Comment by berndmoos** [comment]
Close this for reasons of obscurity
