### ISSUE TITLE
Import for segmented transcriptions (EXS)

### ISSUE THREAD

**Issue by hannahedeland** [Exmaralda-Org/exmaralda#6]
With handling of overlapping segmented speech problems (sorting of segment boundaries along the common timeline).

**Comment by berndmoos** [comment]
First attempt: File > Import... > EXMARaLDA Segmented Transcription, Hanna must check!

**Comment by berndmoos** [comment]
@hannahedeland : Kannst Du mal ausprobieren bitte?

**Comment by hannahedeland** [comment]
We'd probably still need a message for all cases where sorting is not possible. And some problems now surfaced: For two HIAT utterances overlapping another two utterances in one event per speaker, the second utterance is lost - but the Äußerungsendzeichen is kept - in the tok layer. For one HIAT utterance overlapping another, i.e. only words overlapping, there is no segmentation of the event and the Äußerungsendzeichen is kept in the tok layer.

**Comment by berndmoos** [comment]
Closing this, seems to work somehow
