### ISSUE TITLE
Maintenance > Segment transcriptions: no segment counts or "segmented = true" written

### ISSUE THREAD

**Issue by hannahedeland** [Exmaralda-Org/exmaralda#66]
When a corpus contains only basic transcriptions, it is not possible to add segmented transcriptions with the maintenance function, since the read-only information and the "segmented = true" is then missing. With "Update segment counts" the first problem is solved, but still, no "segmented = true" is written, and EXAKT can't find the exs files. The "Create corpus from transcriptions" can segment properly though.

**Comment by berndmoos** [comment]
Found the place where segmented=true should be written and fixed it. What is "read-only" information?

**Comment by Herrner** [comment]
The segment count is read-only-information (can't be changed in Coma's UI - attribute names start with a hash-sign)

**Comment by berndmoos** [comment]
@hannahedeland : okay now?

**Comment by Herrner** [comment]
@hannahedeland okay now?

**Comment by hannahedeland** [comment]
the main problem with segmented=true is fixed, the segment counts still have to be added manually through "Update segment counts"

**Comment by Herrner** [comment]
Closing the issue. I don't know whether segment counts should be added automatically.
