### ISSUE TITLE
CHAT import not working

### ISSUE THREAD

**Issue by Herrner** [Exmaralda-Org/exmaralda#99]
Importing a .cha-File in PE results in a "String index out of range: -1"-Error. File will open in CHAT. Saving the file in CHAT does not help. Same error occurs in TEIdrop.

Exmaple: https://corpus1.mpi.nl/ds/asv/?4&openhandle=hdl:1839/00-0000-0000-0008-7CF8-E

**Comment by berndmoos** [comment]
This is what the CHAT manual says:

> In order to link segments of the transcript to stretches of digitized audio and video, CHAT uses the following notation: 
> 
> `Time Alignment ·%mov:”file”_0_1073`
> 
> This marker can include either %mov information for a digitized video file or **%snd** information for a digitized audio file.

**Comment by berndmoos** [comment]
This is the first line of liean11a.1.cha from the ESF corpus:

`*SAN: i want one # er in@s pianto@s [:=T system]. %snd: "liean11a.wav" 9383 13613`

The underscores required by the CHAT specifications are missing, this is what causes the error message.

**Comment by berndmoos** [comment]
Running CLAN's check command on the file throws a million error messages.

**Comment by berndmoos** [comment]
Nothing to fix about the importer. It's the CLAN files that shoud be fixed. Changing the error message in EXMARaLDA accordingly. N.B.: (MacWhinney 2017)

> The process of integration of TalkBank with CLARIN can also be viewed from a slightly different perspective. In addition to making sure that TalkBank aligns with CLARIN standards, we can consider how CLARIN could benefit more fully from TalkBank as a model. First, if CLARIN could adopt the CHAT coding system as the default for data representation for spoken language, it would greatly enhance the value of its resources. Such a step would require buy-in from many parties and additional work in reformatting, but it would be a major step forward.

**Comment by berndmoos** [comment]
Take that and close:

![image](https://user-images.githubusercontent.com/13796493/27033518-ed6d9152-4f79-11e7-996a-3a6ef174a094.png)

**Comment by berndmoos** [comment]
N.B. Same file via Talkbank (instead of via MPI-TLA) seems okay
